### PR TITLE
Adding openjdk as selenium2 dependency

### PR DESCRIPTION
**Pull request by asgorobets**
Looks like there is no java by default on some ubuntu images we're using here and there. While trying to backport testing scripts from cibox into an existing project with existing Vagrant I found that java was not installed, and it's a real dependency for Selenium 2.

Hope it makes sense to add it as dependency in ansible-behat-selenium2 role.

### CODE REVIEW

**Comment by podarok** [comment]
retest this please

**Comment by ygerasimov** [comment]
I would recommend to go with docker container instead of setting up all components separately

**Comment by Sanchiz** [comment]
retest this please

**Comment by asgorobets** [comment]
retest this please

**Comment by Sanchiz** [comment]
@asgorobets It should be updated with upstream. Now this file lives at https://github.com/propeoplemd/cibox/blob/master/core/cibox-behat-selenium2/defaults/main.yml

**Pull request merged**
