### PR TITLE
Architecture rebuild

### PR DESCRIPTION
**Pull request by Sanchiz**
# CIBox roles API:
cibox_core_roles_api

# Current structure:
## Here you can review files tree https://github.com/Sanchiz/cibox/tree/architecture
- I would recommend to put into `services` folder playbooks, instead of wrapping them into folders. In case when we wrap each service into folder, in all places and roles we should add additional `../` in path to role. We can do this if it is ok.
- `configs` folder in `services` folder is mine. It is not committed.

image

# TODOs(I would like to implement them it another PRs):

- create `github.yml` in `services` folder and move all logic into `cibox-github` role
- define API for Vagrant folders

### CODE REVIEW

**Comment by Sanchiz** [comment]
retest this please

**Comment by podarok** [comment]
We definitely should discuss update path before merging this

**Comment by Sanchiz** [comment]
@podarok Sure!

**Comment by Sanchiz** [comment]
retest this please

**Pull request merged**
