### PR TITLE
Enable APC for PHP via ini file

### PR DESCRIPTION
**Pull request by M1r1k**

### CODE REVIEW

**Comment by podarok** [comment]
@M1r1k do we need to disable opcache , because it is enabled by default for recent php versions?

**Comment by podarok** [comment]
Otherwise apc will start to conflict with opcache

**Comment by M1r1k** [comment]
aha
here we go - another problem with using different Ubuntu versions

Vagrant has php and requires 5.4 APC, when CIBOX uses LTS with php 5.5

**Comment by podarok** [comment]
retest this please

**Pull request merged**
