### PR TITLE
#334: Drupal 8 drush support

### PR DESCRIPTION
**Pull request by Sanchiz**
Issue #334

### CODE REVIEW

**Comment by podarok** [comment]
@Sanchiz add please a task for dispaying drush version, used for a build

**Comment by podarok** [comment]
for ability to catch it here http://128.199.55.125:8080/job/VM_PR_BUILDER/395/console

**Comment by Sanchiz** [comment]
@podarok in `cibox-drush` role? Please describe a little bit more.

**Comment by podarok** [comment]
@Sanchiz yeah, in that role. Just return ```drush --version``` for getting it logged via ansible

**Comment by podarok** [comment]
Add how-to install drush 8

**Pull request merged**
