### PR TITLE
Fix security review notice

### PR DESCRIPTION
**Pull request by Sanchiz**
Fix notice in security report:
```
Directory ~/.drush/cache/default exists, but is not writable. Please check directory permissions.
```

### CODE REVIEW

**Comment by podarok** [comment]
@Sanchiz let's change folder permissions instead of running drush via sudo

**Comment by Sanchiz** [comment]
@podarok Do you mean this this script before this command?

**Comment by podarok** [comment]
@Sanchiz yup. Just chmod/chown

**Comment by Sanchiz** [comment]
@podarok let's merge this PR.
There's some points why we should merge it:
1) There's no way to easy way to get home folder(when you use `sudo` there should be workaround to get sudoed user home dir)
2) Other parts of the system are using `sudo` for drush commands

**Pull request merged**
